spring:
  datasource:
    url: jdbc:mysql://localhost:3306/gc_coffee?useSSL=false&serverTimezone=UTC
    username: coffee
    password: 1111
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
